name: make-test

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  make-test:
    runs-on: ubuntu-latest
    container: ${{ inputs.os }}
    steps:
    - name: Install git
      run: dnf install -y git
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Install dependencies
      uses: ./.github/actions/install-dependencies
    - name: Mark github workspace as safe
      run: git config --system --add safe.directory $PWD
    - name: make test
      run: make test
